@startuml time-bomb-state-diagram
[*] --> Armed
state Armed {
    [*] --> WaitForButton
    Armed --> Defused : right button press
    state WaitForButton {
        WaitForButton : entry / set LED green
        WaitForButton : exit / set LED off
        WaitForButton --> Blink : left button press / set blink counter to 5
    }
    state Blink {
        Blink : entry / set LED red; start blink timer (500ms)
        Blink : exit / set LED off
        Blink --> Pause : blink timeout
    }
    state PauseChoice <<choice>>
    state Pause {
        Pause : entry / start pause timer (500ms)
        Pause --> PauseChoice : pause timeout / decrement blink counter
        PauseChoice --> Blink : [blinkCounter > 0]
        PauseChoice --> Boom : [blinkCounter == 0]
    }
}
state Defused {
    Defused : entry / set LED blue
    Defused : exit / set LED off
    Defused --> WaitForButton : right button press
}
state Boom {
    Boom : entry / set LED white
}
@enduml