@startuml time-bomb-state-diagram
[*] --> Armed
state Armed {
    [*] --> WaitForButton
    state WaitForButton {
        WaitForButton : entry / set LED green
        WaitForButton : exit / set LED off
    }
    state Blink {
        Blink : entry / set LED red; start blink timer (500ms)
        Blink : exit / set LED off
    }
    state Pause {
        Pause : entry / start pause timer (500ms)
    }
    state PauseChoice <<choice>>
}
state Defused {
    Defused : entry / set LED blue
    Defused : exit / set LED off
}
state Boom {
    Boom : entry / set LED white
}
Armed --> Defused : right button press
Defused --> WaitForButton : right button press
PauseChoice --> Boom : [blinkCounter == 0]
WaitForButton --> Blink : left button press / set blink counter to 5
Blink --> Pause : blink timeout
Pause --> PauseChoice : pause timeout / decrement blink counter
PauseChoice --> Blink : [blinkCounter > 0]
@enduml